version: '3.7'

volumes:
    database_data:
        driver: local

services:
    db:
        image: 'postgres:latest' #use latest official version
        expose:
            - 5432
        env_file:
            database.env  # configure postgres
        volumes:
            - database_data:/var/lib/postgresql/data # persist data even if container shuts down

    web:
        depends_on:
            - db
        container_name: thealth-backend
        build: ./
        expose:
            - 3000
        ports: 
            - 3000:3000
        env_file:
            - database.env #configure postgres
        environment: 
             PORT: 3000
        volumes:
                - ./:/go/src/github.com/IamNator/thealth:rw
    
    frontend:
        # depends_on: 
        #     - web
        container_name: thealth-frontend
        build: ./frontend/.
        # expose: 
        #     - 80
        ports: 
            - 4000:80
        volumes: 
            - ./frontend/thealth/dist:/usr/share/nginx/html/dist:rw
            - ./frontend/thealth/index.html:/usr/share/nginx/html/index.html:rw

# Networks to be created to facilitate communication between containers
networks:
    fullstack: