version: '3.7'

volumes:
    database_data:
        driver: local

services:
    db:
        image: 'postgres:latest' #use latest official version
        expose:
            - 5432
        env_file:
            database.env  # configure postgres
        volumes:
            - database_data:/var/lib/postgresql/data # persist data even if container shuts down

    web:
        container_name: thealth
        build: ./
        expose:
            - 3000
        ports: 
            - 3000:3000
        environment:
            PORT: 3000
        env_file:
            - database.env #configure postgres
        volumes:
                - ./:/go/src/github.com/IamNator/thealth:rw
        depends_on:
                - db

# Networks to be created to facilitate communication between containers
networks:
    fullstack: